### ISSUE TITLE
Real bug found in code, inadvertently...

### ISSUE THREAD

**Issue by fge** [intersystems-ru/MonCache#28]
While working on a check giving a huge number of false positives, I came upon this method:

```
ClassMethod isNotValidNumber(nuberString As %String) As %Boolean
{
     return '..isValidNumber(numberString)
}
```

And this is not a false positive: `numberString` is not defined... The argument is named `nuberString` (note the lack of an "m")

**Comment by fge** [comment]
Note, the function immediately below suffers the same problem!

**Comment by daimor** [comment]
fixed
